# Generated by Django 5.0.4 on 2024-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255)),
                ('tidx', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('purchase_order_id', models.CharField(max_length=255)),
                ('purchase_order_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
