# Generated by Django 5.0.4 on 2024-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_book_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='test_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
