# Generated by Django 5.0.4 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_invoice_booking_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='current_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='newest_fee',
            field=models.IntegerField(),
        ),
    ]
