# Generated by Django 5.0.4 on 2024-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_listeningdate_listeningtime_writingdate_writingtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('current_fee', models.IntegerField()),
                ('newest_fee', models.IntegerField()),
                ('test_type', models.CharField(choices=[('paper', 'IELTS on Paper'), ('computer', 'IELTS on Computer'), ('visa', 'IELTS for Visas and Immigration'), ('lifeskill', 'IELTS Life Skills')], max_length=20)),
                ('test_model', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='dates_listening',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='dates_writing',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='times_listening',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='times_writing',
        ),
        migrations.DeleteModel(
            name='ListeningDate',
        ),
        migrations.DeleteModel(
            name='WritingDate',
        ),
        migrations.DeleteModel(
            name='ListeningTime',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='WritingTime',
        ),
    ]
