# Generated by Django 5.0.4 on 2024-04-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_student_options_student_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_partner',
        ),
        migrations.RemoveField(
            model_name='student',
            name='partner_contact_person',
        ),
    ]
