# Generated by Django 5.0.4 on 2024-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
