# Generated by Django 5.0.4 on 2024-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
