# Generated by Django 5.0.4 on 2024-04-26 11:11
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_customuser'),
    ]

    operations = [
        # Add operations here
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20),  # Modify the field as needed
        ),
    ]
