# Generated by Django 5.0.4 on 2024-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('identity_image', models.ImageField(upload_to='identity_images/')),
            ],
        ),
    ]
