# Generated by Django 5.0.4 on 2024-04-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_customuser_delete_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='partner_id',
        ),
    ]
