# Generated by Django 5.0.4 on 2024-04-29 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_customuser_partner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='exam_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='test_city',
            field=models.CharField(choices=[('ktm', 'Kathmandu'), ('pokhara', 'Pokhara')], max_length=100),
        ),
    ]
