# Generated by Django 5.0.4 on 2024-04-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_booking_exam_date_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
