# Generated by Django 5.0.4 on 2024-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='booking',
            name='test_city',
            field=models.CharField(choices=[('ktm', 'Kathmandu')], max_length=100),
        ),
    ]
