# Generated by Django 5.0.4 on 2024-05-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_booking_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('test_city', models.CharField(choices=[('ktm', 'Kathmandu')], max_length=100)),
                ('signature', models.FileField(upload_to='signatures/')),
                ('signature_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('test_model', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('computer', 'Computer-delivered'), ('paper', 'Paper-based')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
