# Generated by Django 5.0.4 on 2024-05-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_bookings_delete_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
