# Generated by Django 5.0.4 on 2024-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_profile_created_at_profile_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('partner', 'Partner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
