# Generated by Django 5.0.4 on 2024-05-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
