# Generated by Django 5.0.4 on 2024-04-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_loginform_signupform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('test_city', models.CharField(max_length=100)),
                ('signature', models.FileField(upload_to='signatures/')),
                ('signature_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('test_model', models.CharField(choices=[('academic', 'Academic'), ('general', 'General Training')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('computer', 'Computer-delivered'), ('paper', 'Paper-based')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginForm',
        ),
        migrations.DeleteModel(
            name='SignupForm',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
