# Generated by Django 5.0.4 on 2024-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_booking_delete_loginform_delete_signupform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
