# Generated by Django 5.0.4 on 2024-04-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_examtype_remove_exam_dates_listening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('LRW', 'LRW'), ('Listening', 'Listening')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.examtype')),
            ],
        ),
    ]
