# Generated by Django 5.0.4 on 2024-04-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_testschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='exam_type',
            field=models.ForeignKey(choices=[('paper', 'IELTS on Paper'), ('computer', 'IELTS on Computer'), ('visa', 'IELTS for Visas and Immigration'), ('lifeskill', 'IELTS Life Skills')], on_delete=django.db.models.deletion.CASCADE, to='website.examtype'),
        ),
    ]
