# Generated by Django 5.0.4 on 2024-04-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20240426_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
