# Generated by Django 5.0.4 on 2024-05-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.customuser'),
        ),
        migrations.AlterField(
            model_name='submittedname',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customuser'),
        ),
    ]
