# Generated by Django 5.0.4 on 2024-05-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_booking_creator_alter_submittedname_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
