# Generated by Django 5.0.4 on 2024-05-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_booking_creator_alter_profile_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('partner', 'Partner')], max_length=20),
        ),
    ]
