# Generated by Django 5.0.4 on 2024-05-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_profile_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('test_city', models.CharField(blank=True, max_length=100)),
                ('passportfile', models.FileField(upload_to='pdf_files/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customuser')),
                ('exam_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.testschedules')),
            ],
        ),
        migrations.DeleteModel(
            name='Blank',
        ),
        migrations.RemoveField(
            model_name='submittedname',
            name='creator',
        ),
        migrations.AlterField(
            model_name='examtype',
            name='test_model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='test_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.examtype'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='SubmittedName',
        ),
    ]
