# Generated by Django 5.0.4 on 2024-05-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_book_delete_blank_remove_submittedname_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='exam_date',
            new_name='test_schedule',
        ),
    ]
